stages:
- build

build:
  image: golang:1-alpine
  stage: build
  tags:
  - amd64
  cache:
    paths:
    - .cache
  before_script:
  - apk add git build-base
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  script:
  - CGO_ENABLED=0 go build -o mautrix-whatsapp-static
  artifacts:
    paths:
    - mautrix-whatsapp-static
    - example-config.yaml
